version: "2"

services:
  novnc:
    build:
      context: .
    ports:
      - "8080:8080"
      - "5900:5900"
      - "3389:3389"
    volumes:
      - ./data/root:/root/
      - ./data/etc/supervisor:/etc/supervisor